STORAGE = 'gcs'

GCS_TFRECORDS_BUCKETNAME = "datasets_bucket_a"
ROOT_TFRECORDS_PATH = "gs://" + GCS_TFRECORDS_BUCKETNAME
TRAIN_TFRECORDS = ROOT_TFRECORDS_PATH + "/training"
VALID_TFRECORDS = ROOT_TFRECORDS_PATH + "/validation"

RESULTS_BUCKETNAME = "dl_training_results"
RESULTS_ROOT = "gs://" + RESULTS_BUCKETNAME
TENSORBOARD_PATH = RESULTS_ROOT + "/tensorboard"
CHECKPOINTS_DIR = "checkpoints"
CHECKPOINTS_PATH = RESULTS_ROOT + "/checkpoints"
MODELS_PATH = RESULTS_ROOT + "/models"
